### ISSUE TITLE
Install Lean4 on old Mac (OS version < 10.15)

### ISSUE THREAD

**Issue by LeanWatch** [leanprover/lean4#1000]
### Description
I've installed elan, and lean4-nightly already.
However, when I run the lean by typing  `lean` on terminal, then I see
following exceptions:
```dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: <my personal folder path>/.elan/toolchains/leanprover--lean4---nightly/bin/../lib/lean/libleanshared.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: <my personal folder path>/.elan/toolchains/leanprover--lean4---nightly/bin/../lib/lean/libleanshared.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

**Expected behavior:** 
What I expected  is, of course, lean4 is working well.

**Actual behavior:**
But as what I've written above, it doesn't work on mac OS version < 10.15

**Reproduces how often:** [What percentage of the time does it reproduce?]

100 %

### Versions

lean itself doesn't work, but I know that its nightly version of lean4.

### Additional Information

There is nothing more. 
My vs code Lean4 extension doesn't work, too, but i guess that above issue causes such problem.

**Comment by Kha** [comment]
We do not support end-of-life OS versions.
